config/routes.rb
Rails.application.routes.draw do
  resources :props
  resources :properties
  devise_for :accounts
  root to: 'public#main'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, 
         :recoverable, :rememberable, :validatable, :confirmable, :trackable

         has_many :properties
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/prop.rb
class Prop < ApplicationRecord
  belongs_to :account
end

app/models/property.rb
class Property < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: %i[ show edit update destroy ]

  # GET /properties or /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1 or /properties/1.json
  def show
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties or /properties.json
  def create
    @property = Property.new(property_params)

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: "Property was successfully created." }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1 or /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: "Property was successfully updated." }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1 or /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: "Property was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def property_params
      params.require(:property).permit(:rooms, :bathrooms)
    end
end

app/controllers/props_controller.rb
class PropsController < ApplicationController
  before_action :set_prop, only: %i[ show edit update destroy ]

  # GET /props or /props.json
  def index
    @props = Prop.all
  end

  # GET /props/1 or /props/1.json
  def show
  end

  # GET /props/new
  def new
    @prop = Prop.new
  end

  # GET /props/1/edit
  def edit
  end

  # POST /props or /props.json
  def create
    @prop = Prop.new(prop_params)

    respond_to do |format|
      if @prop.save
        format.html { redirect_to @prop, notice: "Prop was successfully created." }
        format.json { render :show, status: :created, location: @prop }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @prop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /props/1 or /props/1.json
  def update
    respond_to do |format|
      if @prop.update(prop_params)
        format.html { redirect_to @prop, notice: "Prop was successfully updated." }
        format.json { render :show, status: :ok, location: @prop }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @prop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /props/1 or /props/1.json
  def destroy
    @prop.destroy
    respond_to do |format|
      format.html { redirect_to props_url, notice: "Prop was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prop
      @prop = Prop.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def prop_params
      params.require(:prop).permit(:name, :address, :price, :rooms, :bathrooms)
    end
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  def main
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/props_helper.rb
module PropsHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PropertyFinder</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>

  <body>
    <header>
    <%= render "layouts/nav/public"%>
    </header>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/properties/_form.html.erb
<%= form_with(model: property, local: true) do |form| %>
  <% if property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
        <% property.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :rooms %>
    <%= form.number_field :rooms %>
  </div>

  <div class="field">
    <%= form.label :bathrooms %>
    <%= form.number_field :bathrooms %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/properties/edit.html.erb
<h1>Editing Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Properties</h1>

<table>
  <thead>
    <tr>
      <th>Rooms</th>
      <th>Bathrooms</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.rooms %></td>
        <td><%= property.bathrooms %></td>
        <td><%= link_to 'Show', property %></td>
        <td><%= link_to 'Edit', edit_property_path(property) %></td>
        <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Property', new_property_path %>

app/views/properties/new.html.erb
<h1>New Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rooms:</strong>
  <%= @property.rooms %>
</p>

<p>
  <strong>Bathrooms:</strong>
  <%= @property.bathrooms %>
</p>

<%= link_to 'Edit', edit_property_path(@property) %> |
<%= link_to 'Back', properties_path %>

app/views/props/_form.html.erb
<%= form_with(model: prop, local: true) do |form| %>
  <% if prop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(prop.errors.count, "error") %> prohibited this prop from being saved:</h2>

      <ul>
        <% prop.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :rooms %>
    <%= form.number_field :rooms %>
  </div>

  <div class="field">
    <%= form.label :bathrooms %>
    <%= form.number_field :bathrooms %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/props/edit.html.erb
<h1>Editing Prop</h1>

<%= render 'form', prop: @prop %>

<%= link_to 'Show', @prop %> |
<%= link_to 'Back', props_path %>

app/views/props/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Props</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Price</th>
      <th>Rooms</th>
      <th>Bathrooms</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @props.each do |prop| %>
      <tr>
        <td><%= prop.name %></td>
        <td><%= prop.address %></td>
        <td><%= prop.price %></td>
        <td><%= prop.rooms %></td>
        <td><%= prop.bathrooms %></td>
        <td><%= link_to 'Show', prop %></td>
        <td><%= link_to 'Edit', edit_prop_path(prop) %></td>
        <td><%= link_to 'Destroy', prop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prop', new_prop_path %>

app/views/props/new.html.erb
<h1>New Prop</h1>

<%= render 'form', prop: @prop %>

<%= link_to 'Back', props_path %>

app/views/props/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @prop.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @prop.address %>
</p>

<p>
  <strong>Price:</strong>
  <%= @prop.price %>
</p>

<p>
  <strong>Rooms:</strong>
  <%= @prop.rooms %>
</p>

<p>
  <strong>Bathrooms:</strong>
  <%= @prop.bathrooms %>
</p>

<%= link_to 'Edit', edit_prop_path(@prop) %> |
<%= link_to 'Back', props_path %>